name: Linter CI

on:
  pull_request:
    branches: ["develop"]

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          check-latest: true
      - name: Install dependencies
        run: yarn
      - name: Lint
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: develop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          TYPESCRIPT_ES_CONFIG_FILE: package.json
          TYPESCRIPT_DEFAULT_STYLE: prettier
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_CSS: false
  automerge:
    permissions: write-all
    name: Auto merge
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Merge branch
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "automerge 🔀"
